version: '3.3'

services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000" # Ensure port 9000 is exposed for datanode communication
    environment:
      CLUSTER_NAME: test
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      NAMENODE_URI: hdfs://namenode:9000
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    depends_on:
      - namenode

  flask:
    build: ./app
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - namenode
      - datanode
    environment:
      HADOOP_HOME: /opt/hadoop
    command: python3 app.py

volumes:
  hadoop_namenode:
  hadoop_datanode:
